server:
  port: 8086
  servlet:
      context-path: /
      forward-headers-strategy: framework

spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: order-topic
    topics:
      order-status: order-status-topic
    producer:
      client-id: order-producer
      buffer-memory: 33554432
      batch-size: 16384
      acks: 1
      compression-type: gzip
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      client-id: order-status-listener
      enable-auto-commit: false
      group-id: order-status-group

springdoc:
    swagger-ui:
        tagsSorter: alpha
        operations-sorter: method

swagger:
    info:
        title: "Каfka Vanil with basic broker's features - Order Service"
        description: "Модуль по созданию новых заказов и вычитывания статуса новых заказов"