server:
  port: 8086
  servlet:
      context-path: /
      forward-headers-strategy: framework

spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: order-topic
    producer:
      bootstrap-servers: localhost:9092
      client-id: order-producer
      buffer-memory: 33554432
      batch-size: 16384
      acks: 1
      compression-type: gzip
      retries: 3

    consumer:
      client-id: order-status-listener
      enable-auto-commit: false
      group-id: order-status-group

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration


kafka:
  topics:
    order-status: order-status-topic
    order: order-topic


springdoc:
    swagger-ui:
        tagsSorter: alpha
        operations-sorter: method

swagger:
    info:
        title: "API News Service"
        description: "Backend сервис для приложения «Новостной сервис»"
