server:
  port: 8080
  servlet:
      context-path: /
      forward-headers-strategy: framework


spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: order-status-topic
    topics:
      order: order-topic
    producer:
      client-id: order-status-producer
      compression-type: gzip
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      client-id: order-listener
      group-id: order-group

      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
          spring.json.trusted.packages: "com.example.common"

springdoc:
    swagger-ui:
        tagsSorter: alpha
        operations-sorter: method

swagger:
    info:
        title: "Order Status Service"
        description: "Backend сервис отслеживания новых заказов и формрования статуса заказа"

