server:
  port: 8080
  servlet:
      context-path: /
      forward-headers-strategy: framework


spring:
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      order-status: order-status-topic
      order: order-topic
    producer:
      client-id: order-status-producer
      compression-type: gzip
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      client-id: order-listener
      group-id: order-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration

     # transaction-id-prefix: my-transaction



springdoc:
    swagger-ui:
        tagsSorter: alpha
        operations-sorter: method

swagger:
    info:
        title: "Order Status Service"
        description: "Backend сервис отслеживания новых заказов и формрования статуса заказа"
